env:
  - POSTHOG_API_TOKEN=phc_G3bBjrSrhrQ9OsVnLBFGi1OyMxZ7JjX8kkGYo5c2a85
project_name: assemblyai
builds:
  - binary: assemblyai
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -X github.com/AssemblyAI/assemblyai-cli/cmd.PH_TOKEN={{ .Env.POSTHOG_API_TOKEN }}
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: assemblyai
    homepage: "https://www.assemblyai.com/"
    description: "A quick and easy way to test assemblyAI's transcription features on your terminal"
    license: "Apache 2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    test: |
        output = shell_output("#{bin}/assemblyai-cli config 1234567890")
        expected = "Invalid token. Try again, and if the problem persists, contact support at support@assemblyai.com"
        assert_match expected, output

        output = shell_output("#{bin}/assemblyai-cli transcribe 1234567890")
        assert_match "You must login first. Run `assemblyai config <token>`\n", output

        output = shell_output("#{bin}/assemblyai-cli get 1234567890")
        assert_match "You must login first. Run `assemblyai config <token>`\n", output
    tap:
      owner: assemblyai
      name: homebrew-assemblyai
    commit_author:
      name: assemblyai
      email: support@assemblyai.com

nfpms:
  -
    package_name: assemblyai
    homepage: "https://www.assemblyai.com/"
    vendor: AssemblyAI
    maintainer: AssemblyAI <support@assemblyai.com>
    description: "A quick and easy way to test assemblyAI's transcription features on your terminal"
    license: "Apache 2.0"
    bindir: /usr/bin
    section: utils
    contents:
      # - src: ./manpages/goreleaser.1.gz
      #   dst: /usr/share/man/man1/goreleaser.1.gz
      #   file_info:
      #     mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/goreleaser/copyright
        file_info:
          mode: 0644
    formats:
    - apk
    - deb
    - rpm
    dependencies:
    - git
    recommends:
    - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package


checksum:
  name_template: 'checksums.txt'