project_name: assemblyai
builds:
  - binary: assemblyai
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -X github.com/AssemblyAI/assemblyai-cli/utils.PH_TOKEN={{ .Env.POSTHOG_API_TOKEN }}
      - -X github.com/AssemblyAI/assemblyai-cli/utils.SENTRY_DNS={{ .Env.SENTRY_DNS }}
      - -X github.com/AssemblyAI/assemblyai-cli/cmd.VERSION={{ .Tag }}
release:
  prerelease: auto

brews:
  -
    name: assemblyai
    homepage: "https://www.assemblyai.com/"
    description: "A quick and easy way to test assemblyAI's transcription features on your terminal"
    license: "Apache 2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    test: |
        output = shell_output("#{bin}/assemblyai config 1234567890")
        expected = "Invalid token. Try again, and if the problem persists, contact support at support@assemblyai.com"
        assert_match expected, output

        output = shell_output("#{bin}/assemblyai transcribe 1234567890")
        assert_match "You must login first. Run `assemblyai config <token>`\n", output

        output = shell_output("#{bin}/assemblyai get 1234567890")
        assert_match "You must login first. Run `assemblyai config <token>`\n", output
    tap:
      owner: assemblyai
      name: homebrew-assemblyai
    commit_author:
      name: assemblyai
      email: support@assemblyai.compost_install

scoop:
  bucket:
    owner: assemblyai
    name: scoop-assemblyai
  homepage: "https://www.assemblyai.com/"
  description: "A quick and easy way to test assemblyAI's transcription features on your terminal"
  license: "Apache 2.0"

checksum:
  name_template: 'checksums.txt'