env:
  - POSTHOG_API_TOKEN={{ .Env.POSTHOG_API_TOKEN }}

builds:
  - binary: assemblyai-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -X github.com/AssemblyAI/assemblyai-cli/cmd.PH_TOKEN={{ .Env.POSTHOG_API_TOKEN }}
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: assemblyai-cli
    homepage: "https://www.assemblyai.com/"
    description: "A quick and easy way to test assemblyAI's transcription features on your terminal"
    license: "Apache 2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    tap:
      owner: assemblyai
      name: homebrew-assemblyai
    commit_author:
      name: assemblyai
      email: support@assemblyai.com

checksum:
  name_template: 'checksums.txt'