name: Main branch workflow

on:
  push:
    branches: [main]

env:
  BEFORE_SHA: ${{ github.event.before }}
  CI: true
  POSTHOG_API_TOKEN: ${{ secrets.POSTHOG_API_TOKEN }}
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  VERSION: ${{ env.GITHUB_REF_NAME }}

jobs:
  build:
    if: github.event.commits[0].author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BUILD_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      - run: ./build.sh

      - name: Push to main new build
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

