name: Main branch workflow

on:
  push:
    branches: [main]

env:
  BEFORE_SHA: ${{ github.event.before }}
  CI: true
  POSTHOG_API_TOKEN: ${{ secrets.POSTHOG_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '1.14'
          check-latest: true

      - run: go install
      - name: Run my build script
        run: sudo chmod +x build.sh
