name: Release workflow

on:
  push:
    tags:
      - "*"
      
permissions:
  contents: write

env:
  BEFORE_SHA: ${{ github.event.before }}
  CI: true
  POSTHOG_API_TOKEN: ${{ secrets.POSTHOG_API_TOKEN }}

jobs:
  build:
    if: github.event.commits[0].author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BUILD_TOKEN }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
          POSTHOG_API_TOKEN: ${{ secrets.POSTHOG_API_TOKEN }}

